CREATE DATABASE IF NOT EXISTS banco;
USE banco;

CREATE TABLE SUCURSAL (
    NOMBRE       VARCHAR(50)   NOT NULL,
    LOCALIDAD    VARCHAR(50)   NOT NULL,
    ACTIVOS      DECIMAL(15,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (NOMBRE)
);
CREATE TABLE EMPLEADO (
    ID_EMPLEADO        INT          NOT NULL,
    NOMBRE             VARCHAR(50)  NOT NULL,
    TELEFONO           VARCHAR(20),
    FECHA  DATE         NOT NULL,
    ID_JEFE            INT          NULL,
    PRIMARY KEY (ID_EMPLEADO),
    FOREIGN KEY (ID_JEFE) REFERENCES EMPLEADO (ID_EMPLEADO)
);
CREATE TABLE CLIENTE (
    ID_CLIENTE  INT          NOT NULL,
    NOMBRE      VARCHAR(50)  NOT NULL,
    CALLE       VARCHAR(80),
    CIUDAD      VARCHAR(50),
    ID_EMPLEADO INT          NULL,
    PRIMARY KEY (ID_CLIENTE),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
);
CREATE TABLE CUENTA (
    NUM_CUENTA INT           NOT NULL,
    SALDO      DECIMAL(15,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (NUM_CUENTA)
);
CREATE TABLE C_AHORROS (
    NUM_CUENTA    INT          NOT NULL,
    TASAS  DECIMAL(5,2) NOT NULL,
    PRIMARY KEY (NUM_CUENTA),
    FOREIGN KEY (NUM_CUENTA) REFERENCES cuenta (NUM_CUENTA)
);
CREATE TABLE C_CORRIENTE (
    NUM_CUENTA   INT           NOT NULL,
    DESCUBIERTO  DECIMAL(15,2) NOT NULL DEFAULT 0,
    PRIMARY KEY (NUM_CUENTA),
    FOREIGN KEY (NUM_CUENTA) REFERENCES cuenta (NUM_CUENTA)
);
CREATE TABLE PRESTAMO (
    ID_P     INT           NOT NULL,
    IMPORTE         DECIMAL(15,2) NOT NULL,
    NOMBRE_SUCURSAL VARCHAR(50)   NOT NULL,
    PRIMARY KEY (ID_P),
    FOREIGN KEY (NOMBRE_SUCURSAL) REFERENCES SUCURSAL (NOMBRE)
);
CREATE TABLE PAGO (
    ID INT           NOT NULL,
    NUM_PAGO    INT           NOT NULL,
    FECHA       DATE          NOT NULL,
    IMPORTE     DECIMAL(15,2) NOT NULL,
    PRIMARY KEY (ID, NUM_PAGO),
    FOREIGN KEY (ID) REFERENCES PRESTAMO (ID_P)
);
CREATE TABLE CUENTA_CLIENTE (
    NUM_CUENTA          INT  NOT NULL,
    ID          INT  NOT NULL,
    FECHA DATE,
    PRIMARY KEY (NUM_CUENTA, ID),
    FOREIGN KEY (NUM_CUENTA) REFERENCES cuenta (NUM_CUENTA),
    FOREIGN KEY (ID) REFERENCES cliente (ID_CLIENTE)
);
CREATE TABLE CLIENTE_PRESTAMO (
    ID_CLIENTE  INT NOT NULL,
    ID_PRESTAMO INT NOT NULL,
    PRIMARY KEY (ID_CLIENTE, ID_PRESTAMO),
    FOREIGN KEY (ID_CLIENTE)  REFERENCES cliente (ID_CLIENTE),
    FOREIGN KEY (ID_PRESTAMO) REFERENCES PRESTAMO (ID_P)
);
CREATE TABLE PERSONAS_A_CARGO (
    ID_EMPLEADO INT         NOT NULL,
    NOMBRE      VARCHAR(50) NOT NULL,
    PRIMARY KEY (ID_EMPLEADO, NOMBRE),
    FOREIGN KEY (ID_EMPLEADO) REFERENCES EMPLEADO (ID_EMPLEADO)
);